vaultwarden_db_password: ENC[AES256_GCM,data:DsOI8CMwzWBJjMJSOa1a6G2rfP/Z0x8OYILQK+A5PGZm2OP+T85TAl8vShFpNrqikeADva8kr5F3jQdnRzJIPTVmymU1gMFYbW36cizr7aw=,iv:JmgwudFZ2sSa4dTKEwtpHL2mL+15R+sTMZ3Pi9reA3w=,tag:dLphRxwiG1kUlxwn/lI2jw==,type:str]
vaultwarden_admin_token: ENC[AES256_GCM,data:XlNq3WFNQx0+Kd+0RFdTAeEdqWR26PCMaPfbKgrzMUSBq3OOjvgSKbkBMz5gDW77pBjpjCHmnrt/WlGc5QYJVLdTupTfkjWKmqw6DZG75tJLHhFAMnfLcTqU9gu41T/PSvsv8O2vhU38W7ICCpFZEco0g5GrzQ==,iv:tTIBsMLLv9Nc5h47I9x4AlljYgMQAoa50NWvcKfwCCU=,tag:khE1JXWdb8Wkbq581gp2iQ==,type:str]
sops:
    age:
        - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOXNhdlR3Zm1mZ3hyT2hM
            bldCb01URGt5SjRFbGdTdWFkejN0N1YxaVJzCmpSWGk0c0djczR0bWk2aThzK1pj
            dS9vQXByem1VeDdJUDJ2eW9td0VEVkkKLS0tIGZ3N2dtRFBUTnlBL2lVVEJHSkts
            bHYwY0hmMi91Z0Y1ZlhhUCttcHc2dW8KgKl9ipj/SlOR5iw28P5IQxGXN26VfG5r
            qkqNT4oDvmcMhn4YaiSpPTkAmJSn2twc8DynQMrT6RLL68TpRGGM/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T10:06:15Z"
    mac: ENC[AES256_GCM,data:6Kn5YvPBJ2Z6+LkwxQfeaKBv2sYnMIxVGuiliYXL9bT4y1JpQkqOlr++1VkYugv5DQqDDQxSYOafNXVTkzBvKDZgjJk32RCBMfPSBu3Qi1PlZ1EYm3Ichxm7VjzP3FpNQiG6FHb1RabyfoGpa68uy4QrGjCtOk0PLZRje4S1Pec=,iv:91xOmRJr8UsTcAud7/77kt/50mdeDPsBmYMa0+l1vzo=,tag:pIK5cEUZ0PX95x5JPnhf7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
