name: wallabag
services:
  wallabag:
    image: wallabag/wallabag
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${WALLABAG_DB_ROOT_PASS}
      SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
      SYMFONY__ENV__DATABASE_HOST: db
      SYMFONY__ENV__DATABASE_PORT: 3306
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_USER: ${WALLABAG_DB_USER}
      SYMFONY__ENV__DATABASE_PASSWORD: ${WALLABAG_DB_PASS}
      SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
      SYMFONY__ENV__DATABASE_TABLE_PREFIX: "wallabag_"
      SYMFONY__ENV__MAILER_DSN: smtp://127.0.0.1
      SYMFONY__ENV__FROM_EMAIL: wallabag@example.com
      SYMFONY__ENV__DOMAIN_NAME: http://192.168.178.117:8090
      SYMFONY__ENV__SERVER_NAME: "Wallabag"
    ports:
      - "8090:80"
    volumes:
      - /opt/stacks/wallabag/images:/var/www/wallabag/web/assets/images
    depends_on:
      - db
      - redis

  db:
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${WALLABAG_DB_ROOT_PASS}
    volumes:
      - /opt/stacks/wallabag/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--innodb_initialized"]
      interval: 20s
      timeout: 3s

  redis:
    image: redis:alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
