name: ollama
services:
  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama:0.35.1@sha256:292ee7945dfc3d5840a181f3ab86fedb1e66703e02c8af98b50f4da56b7e278c
    restart: unless-stopped
    expose:
      - "11434"
    networks:
      svr1-network:
        ipv4_address: 172.21.255.241
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama ps || exit 1"]
      interval: 30s

volumes:
  ollama_data:

networks:
  svr1-network:
    external: true
