name: ollama
services:
  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama:0.35.0@sha256:2a6e883b917fc543389599dae79918f5cac9e1438890506982f44aa4f5625d01
    restart: unless-stopped
    expose:
      - "11434"
    networks:
      svr1-network:
        ipv4_address: 172.21.255.241
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama ps || exit 1"]
      interval: 30s

volumes:
  ollama_data:

networks:
  svr1-network:
    external: true
