name: ollama
services:
  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama:0.34.4@sha256:8262851b2846b87c649eddf3e76beb270c52f4d1bc94559f47efde16b0841551
    restart: unless-stopped
    expose:
      - "11434"
    networks:
      svr1-network:
        ipv4_address: 172.21.255.241
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama ps || exit 1"]
      interval: 30s

volumes:
  ollama_data:

networks:
  svr1-network:
    external: true
