- name: Copy Vimix cursors archive to remote host
  ansible.builtin.copy:
    src: vimix-cursors.tar.xz
    dest: /tmp/vimix-cursors.tar.xz
    mode: "0644"

- name: Ensure /usr/share/icons/Vimix-cursors exists
  ansible.builtin.file:
    path: /usr/share/icons/Vimix-cursors
    state: directory
    mode: "0755"

- name: Extract Vimix cursors to /usr/share/icons/Vimix-cursors
  ansible.builtin.unarchive:
    src: /tmp/vimix-cursors.tar.xz
    dest: /usr/share/icons/Vimix-cursors
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Remove the Vimix archive after extraction
  ansible.builtin.file:
    path: /tmp/vimix-cursors.tar.xz
    state: absent

- name: Get list of regular users (UID ≥ 1000)
  ansible.builtin.shell: 'awk -F: ''$3 >= 1000 && $1 != "nobody" {print $1}'' /etc/passwd'
  register: regular_users
  changed_when: false
