---
- name: Deploy Paperless-ngx
  ansible.builtin.include_tasks: ../../../../tasks/deploy_stack.yml
  vars:
    service_name: paperless-ngx
    service_secrets: true
    env_template: paperless-ngx.env.j2
