immich_postgres_password: ENC[AES256_GCM,data:vB3pUPJTrQOdwGMFEaYhL2cR/XtLe37G6s5NrzYGduNRyGiX0cXCgD+0kJ1q8R9IILI3UKF9wKINt9cW1YsCvw==,iv:7eEoNEh08gklNG3x2Tcp4rREr1klI1oNDgBHaO80IrQ=,tag:tbnOxhn7ZLHeMnRTM3x+TQ==,type:str]
sops:
  age:
    - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbHhyUlMxcEtYUE90bXRr
        WHpnR3NvcGR5eDBVSlMwZHloblFITHdvaGxNCjdUWnltMEtnbGttU2xsTVdDeHNC
        T1gzcytSR3N3L1FQa2xTZ0tHZkptMlUKLS0tIHhGVHM2Q29aWC9hQmJ4cVl4bHJK
        eWlCTkF2VEdIaDgwTjd1S1o1b1FBUFUKshpvKn3LsfsmS7Q9WirsQiSFuQeYVnYg
        bW48CL4vQ8NqOe6IdMy2rPMKaZgcUecUkHnsoNYE3XFDtnpBlBYwZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T16:06:22Z"
  mac: ENC[AES256_GCM,data:C/4XE2owc8ZwKA73+vMwpYEBJ26g2H1yS6x5gXVwm1Yu5B2WpAPMd18T83drFcTmlwHw9FbLjLi1PQuNXFMIRfEi0ukJFWt5jKla/L7sfEQMKnsil9PFYVROa9usztmPO2Exf7bvBufpLKsj/QD6vfL3DJSxvHLdES2yAsjqvlY=,iv:+yMuxRoSjDa7j0Vgm8kQJl2DCxiojPCPd/s93P/FpLI=,tag:H6KrR72hqCy/po8i0dMITQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
