- name: Setup svr1
  hosts: svr
  roles:
    - role: apt
      tags: apt

    - role: bash
      tags: bash

    - role: cursor
      tags: cursor

    - role: flatpak
      tags: flatpak

    - role: grub
      tags: grub

    - role: locale
      tags: locale

    # working
    - role: ssh
      tags: ssh

    - role: ufw
      tags: ufw

    - role: xrdp
      tags: xrdp

    - role: luks
      tags: luks
