- name: Configure base system
  hosts: svr1
  roles:
    - role: apt
      tags: apt

    - role: bash
      tags: bash

    - role: cursor
      tags: cursor

    - role: flatpak
      tags: flatpak

    - role: grub
      tags: grub

    - role: locale
      tags: locale

    - role: ssh
      tags: ssh

    - role: ufw
      tags: ufw

    - role: vnc
      tags: vnc

    - role: luks
      tags: luks

    - role: suspend
      tags: suspend

    - role: gtk
      tags: gtk

    - role: wol
      tags: wol
      vars:
        wol_interface: enp5s0

    - role: dns
      tags: dns

    - role: docker
      tags: docker
