- name: Configure IONOS VPS front-door
  hosts: vps
  roles:
    - role: ssh
      tags: ssh

    - role: apt-vps
      tags: apt

    - role: shell-vps
      tags: shell

    - role: zswap-vps
      tags: zswap

    - role: wireguard-vps
      tags: wireguard

    - role: landing
      tags: landing

    - role: caddy-vps
      tags: caddy
