services:
  caddy:
    container_name: caddy
    image: caddy:2.11.4@sha256:cfeb0b281bc44a5a51fecde39e9e577c60d863c0b6196e6bbdf58fd00960887f
    restart: always
    ports:
      # - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    expose:
      - "8080"
    networks:
      svr1-network:
        ipv4_address: 172.21.255.238
    dns:
      - 172.21.255.254
    dns_search: # don't append any search domain
      - "."
    volumes:
      - ./conf:/etc/caddy
      # - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:2019/config/"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  caddy_data:
  caddy_config:

networks:
  svr1-network:
    external: true
