---
- name: Configure Dockhand service user
  ansible.builtin.include_tasks: ../../../../tasks/service_user.yml
  vars:
    service_name: dockhand
    service_uid: 905
    service_dirs:
      - /opt/stacks/dockhand/data

- name: Deploy Dockhand
  ansible.builtin.include_tasks: ../../../../tasks/deploy_stack.yml
  vars:
    service_name: dockhand
