---
- name: Configure Dockhand service user
  block:
    - name: Create dockhand group
      ansible.builtin.group:
        name: dockhand
        system: true
        gid: 905
        state: present

    - name: Create dockhand user
      ansible.builtin.user:
        name: dockhand
        system: true
        uid: 905
        group: dockhand
        create_home: false
        shell: /usr/sbin/nologin
        state: present
