- name: Install packages
  become: true
  register: output_apt_install
  ignore_errors: true
  ansible.builtin.apt:
    update_cache: false
    autoremove: true
    name:
      - ansible
      - ansible-core
      - ansible-lint
      - btop
      - build-essential
      - ca-certificates
      - clang
      - clangd
      - clevis
      - clevis-initramfs
      - clevis-luks
      - clevis-tpm2
      - cmake
      - cryptsetup
      - curl
      - dislocker
      - dkms
      - exfatprogs
      - fail2ban
      - fastfetch
      - ffmpeg
      - ffmpegthumbnailer
      - firefox
      - flatpak
      - git
      - gnome-software-plugin-flatpak
      - initramfs-tools
      - locales
      - net-tools
      - ninja-build
      - ovmf
      - ovmf
      - pkg-config
      - python3
      - python3-ansible-runner
      - python3-apt
      - python3-cryptography
      - python3-cssutils
      - python3-git
      - python3-gitlab
      - python3-gpg
      - python3-numpy
      - python3-pandas
      - python3-pip
      - python3-requests
      - python3-tqdm
      - python3-venv
      - rdesktop
      - rsync
      - spice-vdagent
      - ssh
      - strace
      - ufw
      - util-linux
      - vnstat
      - wget
      - wireguard
      # - xrdp
      - zram-tools

- name: Show apt install output
  ansible.builtin.include_tasks: view_logs.yml
  vars:
    output: "{{ output_apt_install }}"
