- name: Remove unwanted default packages
  become: true
  register: output_apt_remove
  ansible.builtin.apt:
    autoremove: true
    purge: true
    state: absent
    update_cache: true
    name:
      - evolution
      - firefox-esr
      - gnome-calendar
      - gnome-characters
      - gnome-clocks
      - gnome-contacts
      - gnome-font-viewer
      - gnome-maps
      - gnome-music
      - gnome-snapshot
      - gnome-sound-recorder
      - gnome-tour
      - gnome-weather
      - libreoffice*
      - malcontent
      - shotwell
      - totem
      - xterm
      - yelp

- name: Show apt remove output
  ansible.builtin.include_tasks: view_logs.yml
  vars:
    output: "{{ output_apt_remove }}"
