- name: Ensure APT directories exist
  ansible.builtin.file:
    path: "/etc/apt/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - keyrings
    - preferences.d
    - sources.list.d

- name: Copy APT configuration directories
  ansible.builtin.copy:
    remote_src: false
    src: "etc/apt/{{ item }}"
    dest: "/etc/apt/"
    mode: "0644"
    owner: root
    group: root
  loop:
    - keyrings
    - preferences.d
    - sources.list.d
