---
- name: Disable IPv6 system-wide
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-disable-ipv6.conf
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
    owner: root
    group: root
    mode: "0644"
  notify: Reload sysctl

- name: Allow binding to non-local IPs (dnscrypt-proxy on bridge gateway)
  ansible.builtin.copy:
    dest: /etc/sysctl.d/98-ip-nonlocal-bind.conf
    content: |
      net.ipv4.ip_nonlocal_bind = 1
    owner: root
    group: root
    mode: "0644"
  notify: Reload sysctl
