radicale_users_htpasswd: ENC[AES256_GCM,data:H7SyKcDLZfBLfnQ+hZO8swRiEcAd9ViKa3wVgylLl2XbE3VinqDDj/RF3HrC3+KSrUJbPZv95cWtWXUSw4ELexshuEmvQigu4s20snAE2vizcOSgJfvO+b6eEFVNiWfGHid4EUJ/MRnhbUem,iv:srPZgibKSbx6O+yQuq6TdJ8yJHNppCeO+9iaeqPQh6I=,tag:jhsum3TIj+kmJ7X291h+Jg==,type:str]
sops:
  age:
    - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYmxPRUR3bURqZ05oeU45
        bnZod2R2WkFyWU5qeUJzTVk1TERYS0R3Q1RNCjZYVy9hckZ2NG1SclVFOWMya3Bp
        MGpHMi82ZmhqT0krMzJteTF4Q092d0kKLS0tIEVFUE12V1JPRmtOQTQ3a20zY01z
        R2Fob2NxSVJHYTllWEJLYTR4UFJZSjAKg5b8atOChv6Kp0UmBozE5cfaoZTKGod8
        gpHlbDbqyhIgKWjjz87nCUuuLfCRyrKrqPnB5nOT3MKfA2Bym6ayOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T11:18:06Z"
  mac: ENC[AES256_GCM,data:JeyvRVdrMSS9yu486kblekg/IrJ8Smv5cvCkQF4fa0I3cVqO84e2MVBQs8yn8N1V5WXIRco1+DFxeka30TC5AF4+OoPruwAY7IVT27XmDQyn/mm9zbselEyZYrcOx8HgXMHfzkjjVB07nULJ+L4qwcy6WnoIGAc16Yyfwv1D7kM=,iv:lBg8UUS0nO+oolw7Iog7NjOpD9O+sp1CLz9hzmBmeo8=,tag:oW7PVLxXeM1MrKg7eKKvqQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
