dawarich_postgres_password: ENC[AES256_GCM,data:qZElNcmCICC+htesHnf0UcKENRmMdQVjgqu5is4lH7gaLOEyrXcKQuHzbg5XkyTUHXfor4kh98rYni/0,iv:TvvfqyMmAObTU7x3cbg1I5eAh8JfANTtqbB8xWJ8T0I=,tag:1Z7d9kmzzc7TWiT36HoZlA==,type:str]
dawarich_authentik_client_id: ENC[AES256_GCM,data:sOoenjsu6F0zWgcb5TzPYLZjPjebRal1C8pp6MVa/c2VHIIJoNXdKg==,iv:S6SS2bzgbi0Tl/mSx1TsVUbWeaqeTurLmKXXY7osvUg=,tag:92ygFST6wlfdJi9pzWpnMA==,type:str]
dawarich_authentik_client_secret: ENC[AES256_GCM,data:BUKfknkHmNKC1QueEhrod42BtNx4k2y1wdiPvqhBfixGaJO2pqM0OvSNwHL2W/i2NyJML5CfE9bBXjw2kmeUptT0qHCPDzILVoGu1Xfgt1bLGlobc5gTII6615u9I+XxbaNd1K2s+IZRL+x0LygNeRJ+ibQlLNyveYnkxtPldw0=,iv:n9/8rubGhEcoFJHwfA+VVMGU+bJGnc6DNJnbdsBf780=,tag:aRSn25Bz7JjqfE10OjRJ/w==,type:str]
dawarich_secret_key_base: ENC[AES256_GCM,data:jJobNGZcQEz+NYSH1GeAlYNiAAtZzoC1r79W0aYsQDMoT2wgDbLpI+J7nByYyhflrlEmYlj8eStoZLWR+BUKJR34tMRZX7DdfiGziox3EBuixZRZNoWnFU4tKZ5B3Tx3P3YOxeELnyULc/gclaET52IKFLT4/LymjVXX+SEspc4=,iv:jy8Fr7MUFmEpkHAbTYeRLF8l01qqbKGIDeZJ3fQ15Hs=,tag:1WLLLRzZyn4PcV2ZsQHM3Q==,type:str]
sops:
    age:
        - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMy9pWSs3VUFKMVBqT0tJ
            QTB6azU5MDJ5bTlZN3grUzQ1R0RPMHg5UzBJCitvYW93SFZxMi8yNFNpMkZnWGcw
            YzU5ekowM1ZqNUR0TGxSVU9TQjhaUDAKLS0tIE42YzE5RnJQNDdkc2xhcU81enBM
            dmYzOHhYcG1TZWpKdXVBRWF1b2xnbHMKg+FMzgdStEQlg2nvDV0OOiTh98uAYfDr
            Xb4i93eDs2+7h3e++3/Psy4fmzqAj6P1JOdIo0Cket1MZ4nZHXLuZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f5j6re8fs40wx3pnu9qanc2kggs6pvf3up4lj0p6jrdad583ee7sjayaaa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMlJ0REQwRlpMSHFMQUhy
            L0huU0dxdFNIbHNVdzM1MFlBMWFjWkVvUFVvClJtemVzRHB2dUZNRXFGYjVYZHpr
            eUpDVDVsUXlHUm50UXZHTXVUWm5pVkUKLS0tIHIzYmVjSUV4dWkvZjhlSi9ZdTdz
            TzBTeWFtR25Jb1BvcktyMGlKelhGaEEKHmaS5bLRcFolkWYZsg+YFH8lcZkqX+KS
            6C2DHRaFbcT7x4/o/5V+1FUb5gHj4ZTu9LPc2fJB3Eeglo+WcjPoIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:47:28Z"
    mac: ENC[AES256_GCM,data:oXLafiDzIW+mnsEoPElyZlczT5UmGtnZpWs7b+x4CE+Ckme2X03PutHEtBPzcXcQjkE0dvadYHBa/T8D/DBlLpLhOR/xpB/c0XIhF9GEzPQmEeM98VR+1O2+wwJqxR1Ne0Yp2QcbbhsvRk6b9jHZW6qtQqEzKVISySleQMvuTG8=,iv:cQ50wUlWrDXUrCEPqmGbmKNmLmNUyfc6S85I+S+PDgc=,tag:DoCTGrfDXxdzMUdU8U7lnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
