---
- name: Ensure Caddy config directory exists
  ansible.builtin.file:
    path: /opt/stacks/caddy/conf
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy Caddyfile
  ansible.builtin.copy:
    src: conf/Caddyfile
    dest: /opt/stacks/caddy/conf/Caddyfile
    owner: root
    group: root
    mode: "0400"

- name: Deploy Caddy
  ansible.builtin.include_tasks: ../../../../tasks/deploy_stack.yml
  vars:
    service_name: caddy
    compose_recreate: always
