name: linkwarden
services:
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:v2.14.1@sha256:31cf4bd2a2e111991fa5c9de03174c8698869c83722105c6ce529e4c911e6861
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      default:
      svr1-network:
        ipv4_address: 172.21.255.250
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@linkwarden-postgres:5432/postgres
      NEXT_PUBLIC_OLLAMA_ENDPOINT_URL: http://ollama.lan:11434
      OLLAMA_MODEL: mistral
    volumes:
      - ./data:/data/data
    depends_on:
      - linkwarden-postgres
      - linkwarden-meilisearch
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  linkwarden-postgres:
    container_name: linkwarden-postgres
    image: postgres:16-alpine@sha256:16bc17c64a573ef34162af9298258d1aec548232985b33ed7b1eac33ba35c229
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  linkwarden-meilisearch:
    container_name: linkwarden-meilisearch
    image: getmeili/meilisearch:v1.12.8@sha256:c9fac23131cca4db95173d41cc50fd5639121ee381795528fdd7522d7978a7b8
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:7700/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  default:
    driver: bridge
  svr1-network:
    external: true
