---
- name: Include Immich user setup tasks
  ansible.builtin.include_tasks:
    file: user.yml

- name: Deploy Immich
  ansible.builtin.include_tasks: ../../../../tasks/deploy_stack.yml
  vars:
    service_name: immich
    service_secrets: true
    env_template: immich.env.j2
