---
- name: Install APT packages
  become: true
  register: apt_output_install
  ansible.builtin.apt:
    autoremove: true
    state: present
    update_cache: true
    name:
      - build-essential
      - ca-certificates
      - curl
      - fastfetch
      - gdu
      - iputils-ping
      - libssl-dev
      - nftables
      - pkg-config
      - podman
      - rsync
      - rustup
      - vnstat
      - wireguard
      - wireguard-tools

- name: Show apt install output
  ansible.builtin.include_tasks: ../../../../tasks/view_logs.yml
  vars:
    output: "{{ apt_output_install }}"
