name: radicale
services:
  radicale:
    image: ghcr.io/kozea/radicale:3.7.5@sha256:bad5238ac8425c1adf46fc8fc85dca0da4a817ee13e08cd7a68b1fd4997f7cfb
    container_name: radicale
    user: 903:903
    restart: unless-stopped
    networks:
      svr1-network:
        ipv4_address: 172.21.255.234
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    volumes:
      - ./config:/etc/radicale:ro
      - ./data:/var/lib/radicale
    expose:
      - "5232"
    healthcheck:
      test: ["CMD", "/app/bin/python", "-c", "import socket;s=socket.socket();s.settimeout(3);s.connect(('127.0.0.1',5232))"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  svr1-network:
    external: true
