---
- name: Configure Linkwarden service user
  ansible.builtin.include_tasks: ../../../../tasks/service_user.yml
  vars:
    service_name: linkwarden
    service_uid: 908
    service_dirs:
      - /opt/stacks/linkwarden/data

- name: Deploy Linkwarden
  ansible.builtin.include_tasks: ../../../../tasks/deploy_stack.yml
  vars:
    service_name: linkwarden
    service_secrets: true
    env_template: linkwarden.env.j2
