- name: Bind LUKS device to TPM2 using clevis
  become: true
  vars:
    luks_disk: "/dev/nvme0n1p3"
    luks_key_path: "/opt/luks.key"
  block:
    - name: Read the LUKS key from file
      ansible.builtin.slurp:
        src: "{{ luks_key_path }}"
      register: luks_key_data
      no_log: true

    - name: Check if clevis is already bound
      ansible.builtin.command: clevis luks list -d {{ luks_disk }}
      register: clevis_binding_check
      failed_when: false
      changed_when: false

    - name: Bind the LUKS device with TPM2 if not already bound
      ansible.builtin.shell: |
        clevis luks bind -d {{ luks_disk }} tpm2 '{"pcr_bank":"sha256"}' <<< "{{ luks_key_data.content | b64decode }}"
      args:
        executable: /bin/bash
      when: "'tpm2' not in clevis_binding_check.stdout"
      register: clevis_bind_result
      changed_when: "'Successfully bound' in clevis_bind_result.stdout"
      notify: Update initramfs

    - name: List clevis bindings on the LUKS device
      ansible.builtin.command: clevis luks list -d {{ luks_disk }}
      register: clevis_list_output
      changed_when: false

    - name: Show clevis bind result
      ansible.builtin.debug:
        var: clevis_bind_result

    - name: Show clevis list output
      ansible.builtin.debug:
        var: clevis_list_output.stdout
