name: anubis
services:
  anubis:
    container_name: anubis
    image: ghcr.io/techarohq/anubis:v1.27.0@sha256:8828275668b7bc675679f100970f9714f731388fbbf66ae94de8aca952e3fc4a
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      svr1-network:
        ipv4_address: 172.21.255.236
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    environment:
      BIND: ":3000"
      TARGET: "http://caddy.lan:8080"
      COOKIE_DOMAIN: ".${BASE_DOMAIN:?base domain required}"
    healthcheck:
      test: ["CMD", "/ko-app/anubis", "--healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  svr1-network:
    external: true
