name: anubis
services:
  anubis:
    container_name: anubis
    image: ghcr.io/techarohq/anubis:v1.26.0@sha256:c23e455dea15bbd90b512f30aeaa45d76bfe492e001339433ce908dee2e311f8
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      svr1-network:
        ipv4_address: 172.21.255.236
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    environment:
      BIND: ":3000"
      TARGET: "http://caddy.lan:8080"
      COOKIE_DOMAIN: ".bl4ckspell.freeddns.org"
    healthcheck:
      test: ["CMD", "/ko-app/anubis", "--healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  svr1-network:
    external: true
