- name: Get current UFW rules
  ansible.builtin.shell:
    cmd: set -o pipefail && ufw status numbered | grep -E '^\[' | sed 's/\[\s*\([0-9]*\)\].*/\1/' | sort -rn
    executable: /bin/bash
  register: ufw_rule_numbers
  changed_when: false
  failed_when: false

- name: Delete all existing UFW rules
  ansible.builtin.command:
    cmd: ufw --force delete {{ item }}
  loop: "{{ ufw_rule_numbers.stdout_lines }}"
  when: ufw_rule_numbers.stdout_lines | length > 0
  changed_when: true

- name: Enable UFW logging with recommended level
  community.general.ufw:
    logging: medium

- name: Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    default: deny

- name: Set default outgoing policy to allow
  community.general.ufw:
    direction: outgoing
    default: allow

- name: Limit SSH to prevent brute force attacks
  community.general.ufw:
    rule: limit
    port: 22
    proto: tcp
    comment: "Limit SSH access to reduce brute-force attempts"

- name: Allow LocalSend incoming on port 53317
  community.general.ufw:
    rule: allow
    port: 53317
    proto: tcp
    comment: "Allow LocalSend traffic"

- name: Allow TigerVNC incoming on port 5901
  community.general.ufw:
    rule: allow
    port: 5901
    proto: tcp
    comment: "Allow TigerVNC"

- name: Allow HTTP traffic for Nginx Proxy Manager
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
    comment: "Allow HTTP traffic for Nginx Proxy Manager"

- name: Allow HTTPS traffic for Nginx Proxy Manager
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
    comment: "Allow HTTPS traffic for Nginx Proxy Manager"

- name: Allow NPM admin UI traffic on port 81
  community.general.ufw:
    rule: allow
    port: 81
    proto: tcp
    comment: "Allow Nginx Proxy Manager Web UI"

- name: Ensure UFW is enabled
  community.general.ufw:
    state: enabled
