- name: Ensure UFW is enabled
  community.general.ufw:
    state: enabled

- name: Enable UFW logging with recommended level
  community.general.ufw:
    logging: medium

- name: Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    default: deny

- name: Set default outgoing policy to allow
  community.general.ufw:
    direction: outgoing
    default: allow

- name: Limit SSH to prevent brute force attacks
  community.general.ufw:
    rule: limit
    port: 22
    proto: tcp
    comment: "Limit SSH access to reduce brute-force attempts"

- name: Allow LocalSend incoming on port 53317
  community.general.ufw:
    rule: allow
    port: 53317
    proto: tcp
    comment: "Allow LocalSend traffic"

- name: Allow TigerVNC incoming on port 5901
  community.general.ufw:
    rule: allow
    port: 5901
    proto: tcp
    comment: "Allow TigerVNC"

- name: Allow HTTP traffic for Nginx Proxy Manager
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
    comment: "Allow HTTP traffic for Nginx Proxy Manager"

- name: Allow HTTPS traffic for Nginx Proxy Manager
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
    comment: "Allow HTTPS traffic for Nginx Proxy Manager"

- name: Allow NPM admin UI traffic on port 81
  community.general.ufw:
    rule: allow
    port: 81
    proto: tcp
    comment: "Allow Nginx Proxy Manager Web UI"
