---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Server:
    - Essential:
        - Anubis:
            icon: /icons/anubis.png
            description: AI-powered bot protection
            ping: anubis.lan
            statusStyle: "basic"

        - Caddy:
            icon: /icons/caddy.svg
            description: Reverse-Proxy
            ping: caddy.lan
            statusStyle: "basic"

        - Pi-hole:
            icon: /icons/pi-hole.svg
            href: https://pihole.bl4ckspell.de/admin/
            description: DNS Server & Filter
            ping: pihole.lan
            statusStyle: "basic"

    - Documentation:
        - Docs:
            icon: /icons/docusaurus.svg
            href: https://docs.bl4ckspell.de/docs
            description: Home Server Documentation
            ping: docs.lan
            statusStyle: "basic"

    - Management & Monitoring:
        - Dockge:
            icon: /icons/dockge.svg
            href: https://dockge.bl4ckspell.de/
            description: Docker Stacks Management
            ping: dockge.lan
            statusStyle: "basic"

        - Uptime-Kuma:
            icon: /icons/uptime-kuma.svg
            href: https://kuma.bl4ckspell.de/
            description: Status
            ping: kuma.lan
            statusStyle: "basic"

        - Dockhand:
            icon: /icons/dockhand.png
            href: https://dockhand.bl4ckspell.de/
            description: Docker Container Management
            ping: dockhand.lan
            statusStyle: "basic"

    - AI & Data:
        - Ollama:
            icon: /icons/ollama.svg
            description: Local AI models
            ping: ollama.lan
            statusStyle: "basic"

        - Photon:
            icon: /icons/photon.png
            description: Geocoder
            ping: photon.lan
            statusStyle: "basic"

- Services:
    - SSO:
        - Authentik:
            icon: /icons/authentik.svg
            href: https://authentik.bl4ckspell.de/
            description: Login
            ping: authentik.lan
            statusStyle: "basic"

    - Tools:
        - Backrest:
            icon: /icons/backrest.svg
            href: https://backrest.bl4ckspell.de/
            description: Backup management (restic)
            ping: backrest.lan
            statusStyle: "basic"

        - Dawarich:
            icon: /icons/dawarich.svg
            href: https://dawarich.bl4ckspell.de/
            description: Location History Tracker
            ping: dawarich.lan
            statusStyle: "basic"

        - Radicale:
            icon: /icons/radicale.svg
            href: https://radicale.bl4ckspell.de/
            description: CalDAV/CardDAV server
            ping: radicale.lan
            statusStyle: "basic"

        - Forgejo:
            icon: /icons/forgejo.svg
            href: https://forgejo.bl4ckspell.de/
            description: Self-hosted Git forge
            ping: forgejo.lan
            statusStyle: "basic"

        - Immich:
            icon: /icons/immich.svg
            href: https://immich.bl4ckspell.de/
            description: High performance self-hosted photo and video management solution.
            ping: immich.lan
            statusStyle: "basic"

        - Jellyfin:
            icon: /icons/jellyfin.svg
            href: https://jellyfin.bl4ckspell.de/
            description: The Free Software Media System
            ping: jellyfin.lan
            statusStyle: "basic"

        - Linkwarden:
            icon: /icons/linkwarden.svg
            href: https://linkwarden.bl4ckspell.de/
            description: Collect, read, annotate, and preserve your webpages.
            ping: linkwarden.lan
            statusStyle: "basic"

        - Paperless:
            icon: /icons/paperless-ngx.svg
            href: https://paperless.bl4ckspell.de/
            description: Document management
            ping: paperless.lan
            statusStyle: "basic"

        - Vaultwarden:
            icon: /icons/vaultwarden.svg
            href: https://vaultwarden.bl4ckspell.de/
            description: Password manager
            ping: vaultwarden.lan
            statusStyle: "basic"
