- name: Manage ssh systemd service
  ansible.builtin.systemd_service:
    state: started
    name: ssh
    enabled: true
    daemon-reload: true

- name: Ensure sshd_config.d directory exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy custom SSH configuration # verify: $ sshd -T
  ansible.builtin.copy:
    src: files/sshd.conf
    dest: /etc/ssh/sshd_config.d/sshd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart SSH

- name: Add specified SSH keys to root
  ansible.posix.authorized_key:
    user: root
    state: present
    manage_dir: true
    key: "{{ item }}"
  loop: "{{ root_ssh_keys }}"
  vars:
    root_ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKu1vcd8RLWKmfSJlb/i4HXmhs34T+exkmIEWx2yX+C7 bl4ckspell@proton.me"

- name: Copy root's authorized_keys to all regular users
  ansible.builtin.include_tasks: copy_root_keys_to_users.yml
