forgejo_registry_auth: ENC[AES256_GCM,data:Sv4sbn5DF2NlvKE0CJALDEDSAiIteo1rB/DjZEzfZnJIG878BArr8TknHrVidB2ZdVi3eWMTW74BKv3678Y1EICAjqA=,iv:ySua+FCwxE4ivoPCtAcOzGfb71eW7f2H0RR6opm7RP0=,tag:W7e2p+iKb3Tpi9S27kdvCw==,type:str]
sops:
    age:
        - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaXNUcVdqWXU1cjhkSWxn
            dVJIY3EyWkZKUzRObzJoQm9MUnd2M0hnK2g4Ci9vQ1B4bWo5S0NVcWt5d1hsQjho
            Rm5zL29KMS9aS25haU5uZTJCMUpNRjQKLS0tIFU3ZVMrc29odVFpc3JPcWdvK2t2
            ejBrbzYxS2lrM0JTbXJNanBGL2loVG8K+SUl7bj7cDsUNvosJ0Av12UwRvH58UOE
            ntciBLEMXqbTaCgT28upArJ5xM4QfVU0y2DoRW71+0kAPP8TdPYFuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T14:02:51Z"
    mac: ENC[AES256_GCM,data:FQUHAPjo2bnKuwV4kVf9YKHO8AtNAOPv2FbBUiZ1D7iXu2JOOwzNDcA9XKv7dKss2QnJFolxVcSqsOOpMfxWSF+fIq8e1Jb3emTPggm0Cj3Tg3CbDsjg/fBQHSehPiHAI9codO3DIIJoTvLZ8q3q7RJxfMWhILVNYntSmC0hboU=,iv:v4KQITJbBWhSrM+qzUHD3oEc1SzQUH+U4MlK2+mFYPI=,tag:u+mEnsXPNpPXLCaANYIbwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
