pihole_web_password: ENC[AES256_GCM,data:G1Mj6CUCen8eqT0I8OxevGmPEES9Jo0fA9Izgg+EH9Uh+02H0oeRi+HGg2r6FacMiagAfX3dmv9Vz1Gmo3WrMg==,iv:DwBfFvwfTZzlwFC+e7t0eaum3/VXVmmdVN2psx5LN7Y=,tag:9BcQjS90nz3STSrO4q3zsg==,type:str]
sops:
  age:
    - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YWcxeTVUWHJJeE9rbWZL
        SG5ublpWckNVc3pXQ3M1c0Z3dGFwaE8vUkJzCktub0VPMEg2NmNwWU4vcHFtb2lP
        c2ZKbWZZK0RNRDdMcm1oQk45TW05ekkKLS0tIHhHaTdybU5BTllwRXBQNC9rc21s
        OWo0ZXNXcUtUOXlZa1pmSnZ5azlUalEKCuJjuux5VyU9mn8uYNwRbLbycMy+0ED3
        +VJwrZLnUBYmgLllQJt7jYu5S9a51VtZLwgZYC3k71ele/fFvCaE0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T16:07:55Z"
  mac: ENC[AES256_GCM,data:wm4TOF9ulzjUbLAzJ6DeeLnTgowxKuFdMKtANsPfn1tPL37k84EfyDro+SpdoirOv7IxOXcWZ5Ucut2FelQTqGzlW2vay4O6uEOu9eRZp7PxIZrqIymeFPH9tgi4pdlOSWAEnw4r34dLihQ5TKEbH3OI7A8/RjVKj8ANrQMHqMM=,iv:01ghDWj4JmBv7YM6KISiwBy/FDVAq3+8/dlKiyj/RkQ=,tag:LxKnqYaruXTlP26UnJ7RzA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
