wg_home_private_key: ENC[AES256_GCM,data:ZiK+T4jhvusyh91PFfVlFWoO1Jt7+lcBHPB1QiMmZSfmWSUOVj9sK++ZBHo=,iv:bEWhK4vSlisKwbjOT1LsvJwn7Wf5ARehDdIP8jmXnDc=,tag:Om5vBbgG42qCuHRR96F+MQ==,type:str]
wg_vps_public_key: ENC[AES256_GCM,data:z9vEBg7mSMv+7yFeCtxgp5VyZNbhWzgqWaTW+O5nYHDkfLlwB5MHWRjdF/c=,iv:8TR//9EV/9ukFilRkX774E41VO1qgZJukjK4T1th3YM=,tag:fD6gIWURm9dxdMV6abSWNQ==,type:str]
wg_preshared_key: ENC[AES256_GCM,data:mcYwGTpx19jguP+Z6si1O2JYXrsHG14JnuDxzAwSmTbTcmrBLGhMaGfYTK0=,iv:HqpSREO7R3pmQUn6sBzKQBGPDy+ukfEuprY6bbBpCYg=,tag:KnMyH//quxWf0aI5sPW9LA==,type:str]
wg_vps_endpoint: ENC[AES256_GCM,data:O27phfbYZFTnh1I28xVkk0qSpFg=,iv:fUgCQXmc5kF2IhnsQuZR7HJcFbOtFIoP03kvJtpiur4=,tag:S6WZoC0NT0iCG4Wl49sJ4g==,type:str]
sops:
    age:
        - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibjU1L25LTjB4d0xOUk9Q
            eGZTYmtiL2pWeGVGcXhOQkhNbG5HcUN0cFJRCm1hdXpqM01iVGRVMWtLdjN2TzMr
            c3o3SThwSVY1bGl5bUR0cXNwNGozVzQKLS0tIFd3ZEhaWXJtTnN0OUt5OGduNWU2
            ZnVIUUNsdHk1dkw0NUFqTUxhMGtwT2MKv7qqXKz6Rl14+35/TNFZV1g9K/5SWAv2
            1KjvjjPMm+MN5UqQJRmc0bXWkKBfXeF1DqD2KSMley3sRT8FzVXEmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T14:04:01Z"
    mac: ENC[AES256_GCM,data:24OaZyGwcO7ez8bHG7kbWSvC+of0qcPOsU7zIrRCb0DL7qePuESfVkZbvvQvNcPMf9Uc2kciMs7AGr7pZ40oo5aCBUS720yrl6jcRSvGJXbO/vemCaQab8zZfmbI9w8cy/jjIxdw6Xzt/m0GHKWr5J45WbaLWuW3Mj123iE2CT0=,iv:/yI6sDH3PkeIOGbJeYDGmKx0lXgBRDN69F+M20NxgVw=,tag:0mtgCFsywStNzGhchz3zfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
