name: uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.2
    restart: unless-stopped
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      # Host Port : Container Port
      - 3001:3001
    networks:
      default:
      svr1-network:
        ipv4_address: 172.21.255.248
    dns:
      - 172.21.255.254
    dns_search:
      - "."

networks:
  default:
    driver: bridge
  svr1-network:
    external: true
