name: uptime-kuma
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: docker.io/louislam/uptime-kuma:2.4.0@sha256:91e963bfda569ba115206e843febb446f473ab525add4e08b2b9e3beffa16985
    restart: unless-stopped
    volumes:
      - ./uptime-kuma-data:/app/data
    expose:
      - "3001"
    networks:
      svr1-network:
        ipv4_address: 172.21.255.248
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    healthcheck:
      disable: false

networks:
  svr1-network:
    external: true
