name: docusaurus

services:
  docusaurus:
    image: forgejo.bl4ckspell.freeddns.org/bl4ckspell/home-server-docs:1.0.5
    container_name: docusaurus
    restart: unless-stopped
    networks:
      svr1-network:
        ipv4_address: 172.21.255.233
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    expose:
      - "8349"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8349/"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  svr1-network:
    external: true
