linkwarden_nextauth_secret: ENC[AES256_GCM,data:qyhazXr9FVeWjkbgagCYVCZE5w039iaivQ/EX2ItKiSFC4pHW8vJ5v/IamGsFD4jWeOBm8OFbufwVJTalIIAM2f0LKeGtf8H,iv:FFTa6+eajlvTaCx9gChlenBQoUDyGk1mljl0Cf0mNxI=,tag:5FdULAtArXIRUA9BKp174A==,type:str]
linkwarden_postgres_password: ENC[AES256_GCM,data:DFrwAXl3M0cZTcDhjWp1HSYoQDSXZ2hV0ZrDjafL12+jVg0aqYt6FlqRaBAz6tnHfMRu7V/aJV/s9eEUOjbzOkau6bO9wL5Z,iv:I0647sIARv6arUIpKhu45ZSfqYxTe+Rb61fCjZXrNzI=,tag:neXRCR35fDiuKMtczQf6KQ==,type:str]
linkwarden_meili_master_key: ENC[AES256_GCM,data:N4qpLNqa9XAvqXBR+bU4kLa4Tzmcp6XBEaI7jO8DUEdbU/bvXf6Pa7Clqtvyi41yYgJSV9qMAedm4tzWmsmw2VDUos6V4mnb,iv:JiRuteDrc0Al5SudMFc6NbQfsGddq8QfF61lj0ctMYc=,tag:QIZ4CatfDGQUrliCNquFoA==,type:str]
linkwarden_authentik_issuer: ENC[AES256_GCM,data:FSSd4sv51gReeZ6mXNzw+RUJ8ANH0D0BPDwWTd4xkUft+B1OR8t1PYFajC2hzHUc4eBl/K9Je1Mp8vAlrLTUF9c/,iv:YcfheFxntRSmSnb65WkJxSsebWDP66tzGmANs8PbelM=,tag:X3I6n2hOpmV8bLXNOFuHNw==,type:str]
linkwarden_authentik_client_id: ENC[AES256_GCM,data:UPilBen78NUSGTjXa1LIGmK7m79Lq+MNutymFL+2jYcWZmoXIjNaKg==,iv:uLXqZI9Lweb1+HAvbQpNkZjMqwX6ITHRs3ECHVQW9h0=,tag:BVQ+fxTZyb5tGaijMZUcmA==,type:str]
linkwarden_authentik_client_secret: ENC[AES256_GCM,data:24kaKqmQtl08CyCG+q2tQZXbUUYwDHMmAvbVZaKjHswghUCTEWDbTdM6RQQr9AQ46qalNE37oie4Ud1Qw0ET7dDpHp6D62cMMrJinPgHQ2nl46bXBL2JX7TCSFM29oW/dRfUWa82nzzBFPyAugOrP/W/+oqPpDGs6UhENqQdpKo=,iv:OnWbN2HOH//uUBkBBTAHBsub5ZoBRToyNhdhysnmO0M=,tag:WyddV9cw8PFBEGIqP0bMww==,type:str]
sops:
  age:
    - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT254SjFWc29iSjV0Z0VH
        Y3duLzVTWXA0ZW44TnNOL0FmVzhMQjl4Wm1zCjZHZU5INVFIUVlCaklWZHJUMlJF
        T0ZUUzNoU2hIWHhNN245MEZuc0VSQk0KLS0tIFJRei94MjhOZElqdmNycnR4VDRW
        c3EwWjdka0N5aE5hclFhcktOM3JBaEkKng0SI7Z+tFAZwcPaMAeaqSVwJ9UZa72/
        ETq7cOmlhrjEDLOaFy+koh18lukwsdL55/plELm7BBIcZzmFXARRsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T16:06:56Z"
  mac: ENC[AES256_GCM,data:e/HjZTT77XAiZy26LDCsam3azn4sAVyHrwSB3UiSz5MPiVM7YRX3dlEOqKVqblvyr5IylKvJd9Z2LGrI5JLjUYj61XDxjlO41EfCfhs+LYJt7w1I5xa8W/iu3Joyko7wC4XMgwJSEhrh7X0GvjiV6cwXBcIdQVMQljRDWVFblAw=,iv:A+N/gOdrIt+LarLxiqUBVoAOIJGSrHVG9AcqJv292G4=,tag:A8owH/PD3JWhCB3Zbi2BKg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
