wg_vps_private_key: ENC[AES256_GCM,data:vvVLD4t3fBr75OLC8xHqSBmJBIGJRI/pgwmTa0UTtvQar2QlowrHjwA62m8=,iv:7fykSoC81joJ500ButHNQjRsoNkxk8vFBSIkLB7QmHQ=,tag:IjQm3aGAkOl9zOMb6ubOvw==,type:str]
wg_home_public_key: ENC[AES256_GCM,data:PkleMj5uEym4KHxE8aXcooZqZjpese44Fk5w6aF9N5rvVh026qq+9LQHZ7k=,iv:MGiRAqirQtnF6pSlpiAn/Fif/c+4UyYxpRbFWZ/kGS0=,tag:QT2Mk5kaBGhrp5IUb9cwlg==,type:str]
wg_preshared_key: ENC[AES256_GCM,data:X/sKiM+JrfLn+YlEmhcrS40ZzgIJT4jGzOjcDStBtHLSXfhfslp70vuY6Ec=,iv:bbNS6ilmTklQnlte9uf02j6lASYmlIKOXoYcRSFBwok=,tag:8EhRxJWlYtgwYO5/6GCuwg==,type:str]
sops:
    age:
        - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZVBMSXlGL1JhblY2ak92
            dlJWaUxLUjZRWUx1UFlMMnc5eTFRU25FQVg4CmlxSzB5dlhmL0RYN2lhQnhKVStl
            QW80KzRXMUFKMHZOenJGUm1EQWFvS3cKLS0tIEZGTWJhYXpTeHA3OUl0V3MyQ1BO
            elI3S25tam1PUFpTeFJ3SXNHUWJRdEkKLfeLMHoJuc6eyGNZ0rHudvcNrIUAr9Qd
            vXBNdQmzFBXRZUDcQBXwYD0W7shEpjdKVPY9mC3iw8CNwV8FX/KXiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T14:04:01Z"
    mac: ENC[AES256_GCM,data:jHuHB47Cr7hq8boJdMKkUlKYUc0YDCO8O19vOvS/I9am+zJeavIlBr8FmoF3ukKTGHCGhzCRO6M1cPOYTfULLcRjuErcQQMw9sPNO63Zx+j49IpYk1dLZ96UNtSXvXJRxnjG1yj7QnZduCdr/O1DPx1Hs780iqViZKExX9nliQ0=,iv:ZvZsC+6hrAP7Jk0oBL8BpdYpqap+f808ToAykuAIR2o=,tag:WcUuQc1O5JmU9YgV8dUhOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
