wg_vps_private_key: ENC[AES256_GCM,data:vvVLD4t3fBr75OLC8xHqSBmJBIGJRI/pgwmTa0UTtvQar2QlowrHjwA62m8=,iv:7fykSoC81joJ500ButHNQjRsoNkxk8vFBSIkLB7QmHQ=,tag:IjQm3aGAkOl9zOMb6ubOvw==,type:str]
wg_home_public_key: ENC[AES256_GCM,data:D2cdLk0BcG8QWUocOFXlMedMtAw1lq6COJasb43SGyejD42kfvAR3ZbZgvk=,iv:H7JgOqm1LuwJoYl5Ye7zOdj90XAbzGGxIhP0W97flfI=,tag:M3BPswklGKBpCE0/J1txCg==,type:str]
wg_preshared_key: ENC[AES256_GCM,data:X/sKiM+JrfLn+YlEmhcrS40ZzgIJT4jGzOjcDStBtHLSXfhfslp70vuY6Ec=,iv:bbNS6ilmTklQnlte9uf02j6lASYmlIKOXoYcRSFBwok=,tag:8EhRxJWlYtgwYO5/6GCuwg==,type:str]
sops:
    age:
        - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZVBMSXlGL1JhblY2ak92
            dlJWaUxLUjZRWUx1UFlMMnc5eTFRU25FQVg4CmlxSzB5dlhmL0RYN2lhQnhKVStl
            QW80KzRXMUFKMHZOenJGUm1EQWFvS3cKLS0tIEZGTWJhYXpTeHA3OUl0V3MyQ1BO
            elI3S25tam1PUFpTeFJ3SXNHUWJRdEkKLfeLMHoJuc6eyGNZ0rHudvcNrIUAr9Qd
            vXBNdQmzFBXRZUDcQBXwYD0W7shEpjdKVPY9mC3iw8CNwV8FX/KXiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T11:26:56Z"
    mac: ENC[AES256_GCM,data:I9HT81OYN6mB7VZVzbBYjdmEARHkNo0NrqKwMSwGTbZMnqJwmm/E5XJV49hbOkxTk/wmoFWC3W2Gue9h+wWk+kMeS0ik5s2eDQ4jO0QbqJRqKDSyL/vVk9VMe4UhkkGJNakpIXTXg1MOSHLkQQEou1q/HFo1rCfQO9n7Sr+J2zM=,iv:5crkq+ZZK21ETFtJgKoWsEUzoDo6bqpmbk2lZWhyNGI=,tag:ogI12srnwsqPZ0HKNxahlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
