forgejo_db_password: ENC[AES256_GCM,data:sF4uh2AQ+FntyFj9w5V/e4fBSRmnDiqV6x1y3Dw6sNWdrSxnwro9mit5csS4a91zZTMbllEHyndglkAlaSkfvFeO0KMv/kHn,iv:9oDxpEMaD9ieHwlVqW/Vu0zlJ9Ri6lkx0sRf/s4oe6o=,tag:cpWOfHXbaJVV5iqNFOdp9Q==,type:str]
sops:
  age:
    - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNTNnYWJzS3UwRk1CZnNI
        UFNSc1ZuYVZwQURWV2VGT0I0TWV6VmVTSW1VCk5sY0xqS2I0bEVXZEY5NDQ0cG8z
        Q0lONzVVWjZSQ09Jd0FqNk9xVnhsdU0KLS0tIFp1bDA5MW9UTDBuQXdPQ3h5Rzly
        M29aUVY4L3R6VlIyaTQwRUdnWk1EK0kK9OxM9TKS5mwwuqvdglumnL9nXiv370KM
        VVf88XdzrpQjs3nxW1PAFV5zLOJqzRyO072fGTO/1/XoJeqp7yu8NQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T16:05:44Z"
  mac: ENC[AES256_GCM,data:TevEQm0tbF1ZU5lzHTS0J4DmzQgKms+DFzEi7gXmp1vVTacYEkyyzRqyVKg5uxAQI785RR9RMAxuNC8ZTo/Y978UGDF7AlfKnAkDRmEfFmuaNSp6Ippss68tq6cmZAP90a5cYTnVSWuAZGRsg9MHi0MNnZuKPL9VwF+gaMoEdZk=,iv:ZRJPd2HxY1taP89C1+v+eGbvftcnlCQBkWfhawiztn8=,tag:qtSk3FOWEH0zx4ijJ16NDQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
