alias apt="sudo apt"
alias aptu="sudo apt update"
alias aptfg="sudo apt full-upgrade"

alias nala="sudo nala"
alias nfg="sudo nala full-upgrade"

alias c="clear"
alias h="history"
alias uefi="sudo systemctl reboot --firmware-setup"
alias ff="fastfetch"
alias gcl="git clone"
alias cat="batcat"
alias catt='/usr/bin/cat'

alias jf="chown -R jellyfin:jellyfin /srv/jellyfin-media"

alias sd='containers=$(docker ps -q); [ -n "$containers" ] && docker stop $containers; shutdown now'
alias sr='containers=$(docker ps -q); [ -n "$containers" ] && docker stop $containers; systemctl reboot'
alias sn="shutdown now"
