alias sapt="sudo apt"
alias sapta="sudo apt autoremove"
alias saptfg="sudo apt full-upgrade"
alias saptg="sudo apt upgrade"
alias sapti="sudo apt install"
alias saptl="sudo apt list"
alias saptli="sudo apt list --installed"
alias saptlu="sudo apt list --upgradable"
alias saptr="sudo apt remove"
alias saptrp="sudo apt remove --purge"
alias sapts="sudo apt search"
alias saptsw="sudo apt show"
alias saptu="sudo apt update"

alias c="clear"
alias h="history"
alias uefi="sudo systemctl reboot --firmware-setup"
alias ff="fastfetch"
alias gcl="git clone"
alias cat="batcat"
alias catt='/usr/bin/cat'

alias jf="chown -R jellyfin:jellyfin /srv/jellyfin-media"

alias sd='containers=$(docker ps -q); [ -n "$containers" ] && docker stop $containers; shutdown now'
alias sr='containers=$(docker ps -q); [ -n "$containers" ] && docker stop $containers; systemctl reboot'
alias sn="shutdown now"
