name: paperless-ngx
services:
  paperless:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.13
    restart: unless-stopped
    depends_on:
      - paperless-redis
      - paperless-postgres
      - paperless-gotenberg
      - paperless-tika
    expose:
      - "8000"
    networks:
      default:
      svr1-network:
        ipv4_address: 172.21.255.252
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file:
      - .env
    environment:
      PAPERLESS_URL: "https://paperless.bl4ckspell.freeddns.org"
      PAPERLESS_TIME_ZONE: "Europe/Berlin"
      PAPERLESS_OCR_LANGUAGE: "deu"
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-postgres
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
            "openid_connect": {
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "Authentik",
                        "client_id": "${AUTHENTIK_CLIENT_ID}",
                        "secret": "${AUTHENTIK_CLIENT_SECRET}",
                        "settings": {
                            "server_url": "https://authentik.bl4ckspell.freeddns.org/application/o/paperless-ngx/.well-known/openid-configuration"
                        }
                    }
                ],
                "OAUTH_PKCE_ENABLED": "True"
            }
        }
  paperless-redis:
    container_name: paperless-redis
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data
  paperless-postgres:
    container_name: paperless-postgres
    image: docker.io/library/postgres:18.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - pgdata:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PAPERLESS_DBNAME}
      POSTGRES_USER: ${PAPERLESS_DBUSER}
      POSTGRES_PASSWORD: ${PAPERLESS_DBPASS}
  paperless-gotenberg:
    container_name: paperless-gotenberg
    image: docker.io/gotenberg/gotenberg:8.25
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  paperless-tika:
    container_name: paperless-tika
    image: docker.io/apache/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  default:
    driver: bridge
  svr1-network:
    external: true
