- name: Ensure Authentik directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /opt/stacks
    - /opt/stacks/authentik

- name: Load secrets for Authentik
  ansible.builtin.include_vars:
    file: "secrets.yml"
  no_log: true

- name: Create .env file for Authentik
  ansible.builtin.copy:
    dest: /opt/stacks/authentik/.env
    owner: root
    group: root
    mode: "0600"
    content: |
      PG_PASS={{ pg_pass }}
      AUTHENTIK_SECRET_KEY={{ secret_key }}
      COMPOSE_PORT_HTTP=9000
      COMPOSE_PORT_HTTPS=9443
      AUTHENTIK_ERROR_REPORTING__ENABLED=true

- name: Copy Authentik docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/stacks/authentik/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Start Authentik
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/authentik
    state: present
    files:
      - docker-compose.yml
  register: authentik_result

- name: Debug Docker Compose result
  ansible.builtin.debug:
    var: authentik_result
