---
- name: Configure Jellyfin service user
  ansible.builtin.include_tasks: ../../../../tasks/service_user.yml
  vars:
    service_name: jellyfin
    service_uid: 900
    service_dirs: "{{ jellyfin_media_paths }}"
    service_dirs_require_mount: "{{ jellyfin_media_mount }}"

- name: Include Jellyfin watcher setup
  ansible.builtin.import_tasks: jellyfin-watch.yml

- name: Deploy Jellyfin
  ansible.builtin.include_tasks: ../../../../tasks/deploy_stack.yml
  vars:
    service_name: jellyfin
