---
- name: Deploy Jellyfin stack

  vars:
    jellyfin_media_paths:
      - /mnt/wd_red_pro_20tb/jellyfin

  block:
    - name: Create jellyfin group
      ansible.builtin.group:
        name: jellyfin
        system: true
        gid: 900
        state: present

    - name: Create jellyfin user
      ansible.builtin.user:
        name: jellyfin
        system: true
        uid: 900
        group: jellyfin
        create_home: false
        shell: /usr/sbin/nologin
        state: present

    - name: Create media directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: jellyfin
        group: jellyfin
        mode: "0755"
      loop: "{{ jellyfin_media_paths }}"

    - name: Include Jellyfin watcher setup
      ansible.builtin.import_tasks: jellyfin-watch.yml

    - name: Deploy Jellyfin
      ansible.builtin.include_tasks: ../../../../tasks/deploy_stack.yml
      vars:
        service_name: jellyfin
