name: dockhand
services:
  dockhand:
    container_name: dockhand
    image: docker.io/fnsys/dockhand:v1.0.40@sha256:29d4183d8aef2cc7fbc50750fa11434ec331e044647288ae47fe15260e68a44c
    restart: unless-stopped
    user: "1000:1000"
    group_add:
      - "990" # Docker group GID for socket access
    expose:
      - "3000"
    networks:
      svr1-network:
        ipv4_address: 172.21.255.237
    environment:
      DISABLE_LOCAL_LOGIN: false
    dns:
      - 172.21.255.254
    dns_search: # don't append any search domain
      - "."
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data # Must use bind mount, not named volume
      - /opt/stacks:/opt/stacks
    healthcheck:
      disable: false

networks:
  svr1-network:
    external: true
