name: dockhand
services:
  dockhand:
    container_name: dockhand
    image: docker.io/fnsys/dockhand:v1.0.46@sha256:4e0c30e703f1435cd1aacf4948794526dee7c0b4b81b8a992196f1cac53e11d3
    restart: unless-stopped
    user: "905:905"
    group_add:
      - "990" # Docker group GID for socket access
    expose:
      - "3000"
    networks:
      svr1-network:
        ipv4_address: 172.21.255.237
    environment:
      DISABLE_LOCAL_LOGIN: false
    dns:
      - 172.21.255.254
    dns_search: # don't append any search domain
      - "."
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data # Must use bind mount, not named volume
      - /opt/stacks:/opt/stacks
    healthcheck:
      disable: false

networks:
  svr1-network:
    external: true
