paperless_secret_key: ENC[AES256_GCM,data:VlL+87GyAyVW/6kIZismxTCtRIsuSEjguxQzertWbhTG+dmg35GZzZHoLG0l2KQOjD2Vn0KFcXQevrpxSUKHGzM2RjV9OkaiuiBoLhDf91gf3Ociccc+/pk9AjvQ248NwoWK6qOC/wRVwf1bTilDHTq1Mur4NmPaCvGNpl5P/aQ=,iv:6JSfm0rCdkGplY9h8M3ae/g2WAJ7lcl7w/9LTfkQ3jY=,tag:2j0j1tozUCFjGP3IMJJOIQ==,type:str]
paperless_db_name: ENC[AES256_GCM,data:ZouiAcYtoCIa,iv:0InqljjQhWa7Wtp71FJDmdBZYB45PSBnEtQIfIoyPb0=,tag:2HaZZuSnBf5oi+lBTdMbWg==,type:str]
paperless_db_user: ENC[AES256_GCM,data:/qGIUPBT9VRkDbVO,iv:iE712lDaVKnRYuqcY3ZkzYg5Y7lp3hVna+ojsfp5rME=,tag:34Ot+OL4OWJi7q7zr45NWw==,type:str]
paperless_db_password: ENC[AES256_GCM,data:Spd2cGAyW7e+rEUBp9dGz89t9d5o1H7wGaDfX+TnPQNHK0hUlyJIEhqAITPcbGNEhjIfvbEqU4tmvxWbArtnAJFpFZbRMs1XjvPRtwFOpyc=,iv:QMD8UfR3+/IoclUBhmeTeM18Lljwuls1bjp1zvqsBpM=,tag:VbWBQayPq8r7GGsucQZzng==,type:str]
authentik_client_id: ENC[AES256_GCM,data:2VOeJTvJC2j9LBbCQwWsrTIYp3Qi30AuxnHHPaF9usuS40jrTD1Olg==,iv:Z+CvoYdddnjyO7r19czHz8Fi6EeBSImjjFWq+Og0eT8=,tag:KO4eyA1rLt3RsKDJzyQq4A==,type:str]
authentik_client_secret: ENC[AES256_GCM,data:2vNbwKAlyRTSHbujv8hSYRg7J5Bdq31VjIeKP6x5JWB8kdTN8Q41rfWswRrf+qFRYZn67+AFeJcqW+oY0ngy6RPiv8FyGpoRNgk1NgQ86eKHH/cmkxEtzQQpA9uFhVmsm2bdpakoW8tXu+XbEoH1FC05UB8Nnzo9zx4qHuEUTvQ=,iv:PgbCUAaiH9sVHbgdlfKUPx+gDT2INtW/h8IcIlCJCIA=,tag:YPslpjYvRfxMOkgP4XOUxQ==,type:str]
sops:
  age:
    - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N3RWL3FNTURNSzVwNGUz
        SDhCdlgyd3BxYUJpaEw3UWplZFBWRlRrVHdvCjR1aUZuQ3JIbi9MUXQ5ZFE5ZXZS
        N05TdS9ESUVUbGVjRzIxc0FDd0ZNdk0KLS0tIE9ldGYrUWZxK2RudTZiNWxyTEJx
        WnQrK3FKYjlLdW5QUUl6NkxGSkhLbkkKccPosKQv4owMCOdKCdcaxNn3wC+o+YLG
        7ePn07TWeQ9NHPJ1COGOuFItpS3RLLFU7W7b806xlOVFpHFk+prgXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T16:07:31Z"
  mac: ENC[AES256_GCM,data:49qggFBj5ghBVTyJuI8QXYvK7sAKIXhX6yjNpnKX1V4O2sD6+DyQgD9Rc7KendR+Vze+9Xh0LY0axnJzFwPEygTQfExmSj9Rl79YZA2iDc80nsuaeGBjDhhhCUx9IdfY/iUrxJLZ7gdKFW0KYYmXCLGwj2A0rx9uzqT2hhEh6d4=,iv:PS+TOj2WvF18xGGJStv42VvK9DxFWu3K9E8d1fdy+WI=,tag:xKVBwvWSY1ny5nbt66UOpw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
