---
- name: Configure Photon service user
  block:
    - name: Create photon group
      ansible.builtin.group:
        name: photon
        system: true
        gid: 907
        state: present

    - name: Create photon user
      ansible.builtin.user:
        name: photon
        system: true
        uid: 907
        group: photon
        create_home: false
        shell: /usr/sbin/nologin
        state: present
