name: photon
services:
  photon:
    container_name: photon
    image: docker.io/rtuszik/photon-docker:2.3.1@sha256:729f883612bde3215c156111b421d8e0a27b1eb411b92ef4a24bd587b8259b04
    restart: unless-stopped
    environment:
      UPDATE_STRATEGY: PARALLEL
      UPDATE_INTERVAL: 14d
      REGION: europe # Optional: specific region (continent, country, or planet)
      BASE_URL: https://download1.graphhopper.com/public/ # Official
      # BASE_URL: https://r2.koalasec.org/public # Community mirror
      DOWNLOAD_MAX_RETRIES: 5
      FORCE_UPDATE: FALSE
      LOG_LEVEL: INFO
      SKIP_MD5_CHECK: FALSE
      PHOTON_LISTEN_IP: "0.0.0.0"
    volumes:
      - photon_data:/photon/data
    networks:
      svr1-network:
        ipv4_address: 172.21.255.245
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    expose:
      - "2322"
    healthcheck:
      disable: false

volumes:
  photon_data:

networks:
  svr1-network:
    external: true
