pg_pass: ENC[AES256_GCM,data:DI+j4d8/OJFTGabtBRcjM7wPFWa8xpwgqXG/2ZYTrY92s2qklRu0ZeW+OTKQi8KEiQtgX6WYezPZiBIXAsmM1kWvBN9ii3t49kyjJ5xw7fI=,iv:tf2V3XF3kq+RhFGI4UleeXoo3zV+hdqziqzUb/0dpLU=,tag:V0WCMU3ID0hTWMgXAjxvWQ==,type:str]
secret_key: ENC[AES256_GCM,data:UNBBgCo3SVfzwLjOy+sz0CPWiw5j1t78CWU+oO614FASQJkoqy8nKcdDsdqfW/dThf5Pe5NYVAZ201nU,iv:SUD8UsDGQQUACiVAg3C2EFlhu1+EdYfAeFqRTFbeBGY=,tag:KZyZEMsFkkJmLQ7xQ7mF5g==,type:str]
sops:
  age:
    - recipient: age1c99t5d0qkam5aqzrpxhgdexk0ss37jtnqwdzpkvtdfvfp8n5c9dsgnrdfv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNW1SbXdiektvdHQxRmll
        eU1uNlBnWDY4QzdQaXluQ0piMm9aa2UrS1F3ClptazV3amFraDFkeitoMEZwSE1a
        ejBoY2wyY01kb3JKeXlQbWkySjZWQlEKLS0tIGtscmw1ek5TeEM3d1Y5OFVzd08z
        ZnpNVkdvdkJmVWZaQklsaGVSOGhldE0KFbf4/uU6WOkJ1hCH2YA51jp/wBaPJM9y
        lqXwCKWx5RbArEtAHmB/t5/Wuv+FWmKHZUGPEzC2K58vt16MkMPekw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T15:45:50Z"
  mac: ENC[AES256_GCM,data:wzFv4CFjZCrU8F/n5Xsuyap/DmmtFVYhf1rQEK6AUaddrR3sXOwV1KLzPLwmV434M2vqFasyRV/4S8xWvFPrsVLVCD9t4DrmYTiVLxCSJp+VeWfGhx8W7rA8yvl0VGvZmGb14CCzzeZ88FtuwGNQWUocfVSzKKRlq94YvqquvH0=,iv:oaX3htiWFdUn5eVM69WqrA7GpZ3/tKSXLw3mom5NBSo=,tag:S14Ryk0GL+FzvWLLRIL8hA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
